### ISSUE TITLE
Extracting  Base Image 

### ISSUE THREAD

**Issue by allwefantasy** [allwefantasy/mlsql-build#9]
Every time we build the image, we will  do the following steps :

1. apt-get/update the system
2. download jdk
3. download conda

We can extract this steps as a new base image which have lower update frequency to speed up the build flows.
The maybe base image: 

1. mlsql-base-jdk8-conda
2. mlsql-base-jdk14-conda

**Comment by chncaesar** [comment]
Working on it

**Comment by chncaesar** [comment]
Closed , see PR # 10
